# Generated by Django 5.0.4 on 2024-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_managers'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbook',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='mybook',
            name='user',
        ),
        migrations.AddField(
            model_name='mybook',
            name='user',
            field=models.ManyToManyField(related_name='my_books', to='accounts.profile'),
        ),
    ]
