# Generated by Django 5.0.4 on 2024-11-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_adminbook_title_alter_mybook_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbook',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
