# Generated by Django 5.0.4 on 2024-11-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_user_mybook_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybook',
            name='wish_list',
            field=models.BooleanField(default=False),
        ),
    ]
