# Generated by Django 5.0.4 on 2024-11-20 07:21

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_managers_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', accounts.managers.AppUserManager()),
            ],
        ),
    ]
